# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

# name: Deno

# on:
#   push:
#     branches: [main]

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # 步骤名称      
#       - name: Build and Deploy
#         # 该步骤所需的环境变量
#         env:
#           ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
#           # 在部署前要checkout的基本分支，默认是master
#           BASE_BRANCH: main # The branch the action should deploy from.
#           # 指定部署的分支，默认是 gh-pages 分支
#           BRANCH: main # The branch the action should deploy to.
#           # 存储库中要部署的文件夹。
#           # 该步骤会将项目中 FOLDER 指定文件夹下的文件推送到 BRANCH 分支，作为Github Pages 部署的内容。
#           # Vue CLI默认打包到 dist 目录
#           FOLDER: docs # The folder the action should deploy.
#           # 在向 BRANCH 分支推送代码前，可以指定构建脚本
          BUILD_SCRIPT: cd vue-vite && npm install && npm run build # The build script the action should run prior to deploying.

name: buildAndDeploy

env:
  TZ: Asia/Shanghai


on:
  # main
  push:
    branches: [main]

# 开始任务
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      # 安装和构建
      - name: Install and Build
        run: |
          cd vue-vite && yarn
          cd vue-vite && yarn run build
      - name: Update to repository
        env:
          # 你的GitHub名字
          GITHUB_USERNAME: "hlfine"
          # 你的邮箱
          EMAIL: "18035942438@163.com"
          # 作为博客的仓库名
          BLOG_REPO: "hlfine.github.io"
          # GitHub Token
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

        run: |
          git config --global user.email $GITHUB_USERNAME
          git config --global user.name $EMAIL
          cd .. && git init && git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$BLOG_REPO.git" main:main